version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=21March2004@
      - MYSQL_DATABASE=flash_notes
      - SECRET_KEY=your-super-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GOOGLE_API_KEY=AIzaSyBqlzjaRIXpMd45hoOWI11Q0vymzLMNWys
      - AI_PROVIDER=google
      - GEMINI_MODEL=gemini-2.0-flash
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=21March2004@
      - MYSQL_DATABASE=flash_notes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 